#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Quotes.Resource", IsApplication=true)]

namespace Quotes
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int card_flip_left_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int card_flip_left_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int card_flip_right_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int card_flip_right_out = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int fade_in = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int fade_out = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int funny_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int happy_color = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int life_color = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int love_color = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int transparent = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int white = 2131034116;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int author = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int btn_Funny = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int btn_Happy = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int btn_life = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int btn_love = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int card_back = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int container = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int quote = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int card_flip_time_full = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int card_flip_time_half = 2131099649;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int card_back = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int card_front = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int Funny = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int Happy = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int Life = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int Love = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
